### ISSUE TITLE
binary name conflict

### ISSUE THREAD

**Issue by arnottcr** [fatih/motion#11]
this shares a binary name, `motion`, with https://github.com/Motion-Project/motion. I am looking to package this up on arch, and realised there was a conflict. any thoughts?

**Comment by fatih** [comment]
There is not much I can do, unfortunately. What you could do is, to open a PR to `vim-go` where you can change the motion binary path. And then rename the binary, i.e: `motion-vim` or something a like.

**Comment by arnottcr** [comment]
so, the issue is I am trying to package this binary and track it with the system's package manager, for feature updates and bug fixes. currently vim-go simply installs the current version to GOBIN and it never gets updated.
